#ifndef MOTOR_POSITIONS_H
#define MOTOR_POSITIONS_H

//Positions of motors on the 2 boards
//0-9 - Motors on first board
//10-19 - Motors on second board

#define MOTOR_RAIL_LOW_SPEED 0
#define MOTOR_RAIL_HIGH_SPEED 1
#define MOTOR_LINEAR_FEEDER 8
#define MOTOR_FACE_SAW_SPEED 2
#define MOTOR_FACE_SAW_TILT 3
#define MOTOR_CRUSHER 9
#define MOTOR_SUBSAMPLER_ROTATION 4
#define MOTOR_SUBSAMPLER_VERTICAL 5
#define MOTOR_SUBSAMPLE_TRANSFER_VERTICAL 6
#define MOTOR_SUBSAMPLE_TRANSFER_ROTATION 7
#define MOTOR_STORAGE_SYSTEM_ROTATION 10
#define MOTOR_STROAGE_SYSTEM_EJECTION 11
#define MOTOR_STORAGE_SYSTEM_LOCK 12
#define MOTOR_SAMPLE_CLAMP 13

//Crusher Defines
#define MOTOR_CRUSHER_SPEED 0

#endif
