#ifndef TASKDEFS_H
#define TASKDEFS_H

//Error Phase Definition
//Needs to be < -1

#define ERROR_TASK_PHASE -2

//Tasks on all boards/Functions for the GUI

#define TASK_RUN_MOTOR 1
#define TASK_SET_MOTOR_POSITION 2
#define TASK_ABORT_TASK 50
#define TASK_SEND_TASK_STATUS 51
#define TASK_HOLD_MOTOR_POSITION 52
#define TASK_SEND_BOT_STATUS 53
#define TASK_STOP_ALL 54

//Tasks on board zero

#define TASK_PLACE_LINER 100
#define TASK_ACCEPT_CORE 101
#define TASK_TIGHTEN_CLAMP 102
#define TASK_FACE_CORE 103
#define TASK_MOVE_CLAMP 104
#define TASK_STORE_CORE 105
#define TASK_RETRIEVE_CORE 106
#define TASK_RELEASE_CLAMP 108
#define TASK_EMPTY_CLAMP 109
#define TASK_MOVE_TO_SUBSAMPLE_POSITION 110
#define TASK_RESET_ACTUATORS_1 150

//Tasks on board one

#define TASK_GRASP_SAMPLE 200
#define TASK_CUT_SUBSAMPLE 201
#define TASK_CRUSH_SUBSAMPLE 202
#define TASK_TRANSFER_SAMPLE 203
#define TASK_DISCARD_TUBE 204
#define TASK_RESET_ACTUATORS_2 250



//Positions of motors

//Board 0

#define MOTOR_RAIL_LOW_SPEED 0
#define MOTOR_RAIL_HIGH_SPEED 1
#define MOTOR_LINER_FEEDER 2
#define MOTOR_LINER_FEEDER_SOLENOID 3
#define MOTOR_FACE_SAW_DRIVE 4
#define MOTOR_FACE_SAW_TILT 5
#define MOTOR_CORE_CLAMP 6
#define MOTOR_CART_CLAMP_RELEASE 7
#define MOTOR_CORE_CLAMP_STORAGE 8
#define MOTOR_CORE_DUMP 9

//Board 1

#define MOTOR_SUBSAMPLE_ROTATE 0
#define MOTOR_SUBSAMPLE_VERTICAL 1
#define MOTOR_SUBSAMPLE_SAW_DRIVE 2
#define MOTOR_SUBSAMPLE_SQUEEZE 3
#define MOTOR_SAMPLE_TRANSFER_ROTATE 4
#define MOTOR_SAMPLE_TRANSFER_VERTICAL 5
#define MOTOR_SAMPLE_TRANSFER_OPEN_GRIPPER 6
#define MOTOR_SAMPLE_TRANSFER_VIBRATOR 7
#define MOTOR_TUBE_STORAGE_SOLENOID 8
#define MOTOR_CRUSHER 9

//Digital Port numbers

#define PORT_BOARD_INDEX 15

//Board 1

#define PORT_LINER_FEEDER_BREAK_BEAM 0
#define PORT_FACE_SAW_TILT_LIMIT_SWITCH 1
#define PORT_LINEAR_RAIL_INDEX 2
#define PORT_CART_CLAMP_RELEASE_LIMIT 3
#define PORT_CORE_CLAMP_STORAGE_INDEX 4
#define PORT_CORE_DUMP_LIMIT 5

//Board 2

#define PORT_SUBSAMPLE_VERTICAL_LIMIT_LOW 0
#define PORT_SUBSAMPLE_VERTICAL_LIMIT_HIGH 1
#define PORT_SUBSAMPLE_ROTATE_INDEX 2
#define PORT_SUBSAMPLE_SQUEEZE_INDEX 3
#define PORT_SAMPLE_TRANSFER_VERTICAL_LIMIT_LOW 4
#define PORT_SAMPLE_TRANSFER_VERTICAL_LIMIT_HIGH 5
#define PORT_SAMPLE_TRANSFER_ROTATE_INDEX 6
#define PORT_SAMPLE_TRASNFER_VIBRATION_INDEX 7

//Position defines

#define POSITION_SUBSAMPLE_ROTATE_CUT 0
#define POSITION_SUBSAMPLE_ROTATE_CRUSH 0
#define POSITION_SUBSAMPLE_SQUEEZE_OPEN 0
#define POSITION_SUBSAMPLE_SQUEEZE_CLOSED 0
#define POSITION_SUBSAMPLE_VERTICAL_START_CUT 0
#define POSITION_SUBSAMPLE_VERTICAL_END_CUT 0
#define POSITION_SUBSAMPLE_VERTICAL_TRANSFER_TURN 0
#define POSITION_CORE_DUMP_DUMP 0
#define POSITION_CORE_DUMP_NORMAL 0
#define POSITION_CORE_CLAMP_OPEN 0
#define POSITION_CORE_CLAMP_CLOSED 0
#define POSITION_SAMPLE_TRANSFER_VIBRATOR_UP 0
#define POSITION_SAMPLE_TRANSFER_VERTICAL_SOLID_OVER 0
#define POSITION_SAMPLE_TRANSFER_VERTICAL_TRASHCAN 0
#define POSITION_SAMPLE_TRANSFER_VERTICAL_SAFE 0
#define POSITION_SAMPLE_TRANSFER_VERTICAL_SOLID_INSERT 0
#define POSITION_SAMPLE_TRANSFER_VERTICAL_GET_TUBE 0
#define POSITION_SAMPLE_TRANSFER_ROTATE_TRASH 0
#define POSITION_SAMPLE_TRANSFER_ROTATE_TRASH_TUBE 0
#define POSITION_SAMPLE_TRANSFER_ROTATE_PICK_UP_TUBE 0
#define POSITION_SAMPLE_TRANSFER_ROTATE_SOLID 0
#define POSITION_SAMPLE_TRANSFER_ROTATE_SAFE 0
#define POSITION_FACE_SAW_TILT_UP 0
#define POSITION_RAIL_HIGH_SPEED_NEAR_STORAGE 0
#define POSITION_RAIL_HIGH_SPEED_DOCK 0
#define POSITION_CART_CLAMP_RELEASE_LOOSE 0
#define POSITION_CART_CLAMP_RELEASE_TIGHT 0

//Speed defines

//Board 0

#define SPEED_RAIL_LOW_SPEED_MAX 0
#define SPEED_RAIL_HIGH_SPEED_MAX 0
#define SPEED_LINER_FEEDER_PWM 0
#define SPEED_LINER_FEEDER_SOLENOID_PWM 0
#define SPEED_FACE_SAW_DRIVE_MAX 0
#define SPEED_FACE_SAW_TILT_MAX 1000
#define SPEED_CORE_CLAMP_MAX 0
#define SPEED_CORE_CLAMP_MIN 0
#define SPEED_CART_CLAMP_RELEASE_MAX 0
#define SPEED_CORE_CLAMP_STORAGE_MAX 0
#define SPEED_CORE_DUMP_MAX 0


//Board 1

#define SPEED_SUBSAMPLE_ROTATE_MAX 8000
#define SPEED_SUBSAMPLE_VERTICAL_MAX 5000
#define SPEED_SUBSAMPLE_SAW_DRIVE_MAX 0
#define SPEED_SUBSAMPLE_SQUEEZE_MAX 0
#define SPEED_SUBSAMPLE_SQUEEZE_MIN 0
#define SPEED_SAMPLE_TRANSFER_ROTATE_MAX 8000
#define SPEED_SAMPLE_TRANSFER_VERTICAL_MAX 5000
#define SPEED_SAMPLE_TRANSFER_OPEN_GRIPPER_MAX 0
#define SPEED_SAMPLE_TRANSFER_VIBRATOR_MAX 0
#define SPEED_TUBE_STORAGE_SOLENOID_MAX 0
#define SPEED_CRUSHER 0


//Acceleration defines

//Board 0

#define ACCEL_RAIL_LOW_SPEED_MAX 0
#define ACCEL_RAIL_HIGH_SPEED_MAX 0
#define ACCEL_LINER_FEEDER_MAX 0
#define ACCEL_LINER_FEEDER_SOLENOID_MAX 0
#define ACCEL_FACE_SAW_DRIVE_MAX 0
#define ACCEL_FACE_SAW_TILT_MAX 1000
#define ACCEL_CORE_CLAMP_MAX 0
#define ACCEL_CART_CLAMP_RELEASE_MAX 0
#define ACCEL_CORE_CLAMP_STORAGE_MAX 0
#define ACCEL_CORE_DUMP_MAX 0

//Board 1

#define ACCEL_SUBSAMPLE_ROTATE_MAX 8000
#define ACCEL_SUBSAMPLE_VERTICAL_MAX 5000
#define ACCEL_SUBSAMPLE_SAW_DRIVE_MAX 0
#define ACCEL_SUBSAMPLE_SQUEEZE_MAX 0
#define ACCEL_SAMPLE_TRANSFER_ROTATE_MAX 8000
#define ACCEL_SAMPLE_TRANSFER_VERTICAL_MAX 5000
#define ACCEL_SAMPLE_TRANSFER_OPEN_GRIPPER_MAX 0
#define ACCEL_SAMPLE_TRANSFER_VIBRATOR_MAX 0
#define ACCEL_TUBE_STORAGE_SOLENOID_MAX 0
#define ACCEL_CRUSHER 0


#endif
