#ifndef __msimage_HDR__
#define __msimage_HDR__

// GBA image generated by:
//   ppm2gbasrc msimage.ppm

extern const int msimage_nrows;
extern const int msimage_ncols;
extern const unsigned short msimage[158][62];

#endif
