TARGET = libicxportcommon

include ../makefiles/makefile.library

BackgroundGraphics.o:	BackgroundGraphics.cxx ictiles.raw.c

#ictiles.raw.c:	../graphics/ictiles.BMP
#	gfx2gba -m -f src -pictiles.pal ../graphics/ictiles.BMP
